ros1 networking function overhaul

diff --git a/aliases/generic_aliases b/aliases/generic_aliases
--- a/aliases/generic_aliases
+++ b/aliases/generic_aliases
@@ -1,7 +1,4 @@
 # ----- Current -----
-# Git
-alias gitchris='git config --global user.name chriswsuarez && git config --global user.email chriswsuarez@utexas.edu'
-
 # File navigation
 alias ...='cd ../../../'
 alias ....='cd ../../../../'
@@ -87,7 +84,7 @@ alias dcb='docker compose build'
 alias dimg='docker image'
 alias dcnt='docker container'
 alias dload='docker load <'
-alias noetic_docker='xhost +si:localuser:root && cd ~/chris_setup/docker/noetic-desktop/ && docker compose up -d && docker exec -ti noetic-desktop bash'
+alias noetic_docker='xhost +si:localuser:root && cd ~/nrg_setup/docker/noetic-desktop/ && docker compose up -d && docker exec -ti noetic-desktop bash'
 
 # Pkgs
 alias grepdpkg='dpkg -l | grep'
@@ -101,16 +98,72 @@ function cudaenv () {
 
 # Generic ROS 1 Networking
 alias localmaster='export ROS_MASTER_URI=http://localhost:11311 && export ROS_IP=127.0.0.1'
-function rosip () {
-    ROSIP="$(ifconfig | grep -A 1 $1 | tail -1 | cut -c 14- | cut -d " " -f 1)"
-    export ROS_IP=$ROSIP
+function rosmaster () {
+    ROSMASTER="$(getent hosts $1 | cut -d " " -f 1)"
+    reg='^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$'
+    if ! [[ $ROSMASTER =~ $reg ]] ; then
+        echo "Could not find an IP address for host: $1"
+        return 1
+    fi
+
+    export ROS_MASTER_URI=http://$ROSMASTER:11311
+    echo "ROSMASTER set: $ROSMASTER"
+    
+    # lookup this device's IP address on the same subnet
+    i=1
+    LOCALIP="$(hostname -i | cut -d " " -f 1)"
+    while [[ $LOCALIP =~ $reg ]]
+    do
+        if [ "$(echo $ROSMASTER | cut -d "." -f1-3)" == "$(echo $LOCALIP | cut -d "." -f1-3)" ] ; then
+            export ROS_IP=$LOCALIP
+            echo "ROS_IP set: $ROS_IP"
+            return 1
+        else
+            ((i+=1))
+            LOCALIP="$(hostname -i | cut -d " " -f $i)"
+        fi
+
+        if ! [[ $LOCALIP =~ $reg ]] || [[ "$(hostname -i)" != *" "* ]] ; then
+            break
+        fi
+    done
+
+    i=1
+    LOCALIP="$(hostname -I | cut -d " " -f 1)"
+    while [[ $LOCALIP =~ $reg ]]
+    do
+        PREVIP=$LOCALIP
+        if [ "$(echo $ROSMASTER | cut -d "." -f1-3)" == "$(echo $LOCALIP | cut -d "." -f1-3)" ] ; then
+            export ROS_IP=$LOCALIP
+            echo "ROS_IP set: $ROS_IP"
+            return 1
+        else
+            ((i+=1))
+            LOCALIP="$(hostname -I | cut -d " " -f $i)"
+        fi
+
+        if ! [[ $LOCALIP =~ $reg ]] || [[ "$(hostname -I)" != *" "* ]] ; then
+            echo "Could not find a local ip specificed by 'hostname -i' or 'hostname -I' that is on the same subnet as the rosmaster: $ROSMASTER"
+            echo "ROS_IP was not updated"
+            break
+        fi
+    done
 }
 
-function rosmaster () {
-    ROSIP="$(ifconfig | grep -A 1 $1 | tail -1 | cut -c 14- | cut -d " " -f 1)"
-    export ROS_MASTER_URI=http://$ROSIP:11311
-    export ROS_IP=$ROSIP
-}
+# rosmaster bash completion
+_hostnames()
+{
+    local cur prev words cword
+    _init_completion -n = || return
+
+    if [[ $cur == -* ]]; then
+        COMPREPLY=($(compgen -W '$(_parse_usage "$1")' -- "$cur"))
+        return
+    fi
+
+    _known_hosts_real -- "$cur"
+} &&
+    complete -F _hostnames rosmaster
 
 # SSH
 alias sshkeygen='ssh-keygen -t rsa -b 4096'
